#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nltk
Version  : 3.5
Release  : 21
URL      : https://files.pythonhosted.org/packages/92/75/ce35194d8e3022203cca0d2f896dbb88689f9b3fce8e9f9cff942913519d/nltk-3.5.zip
Source0  : https://files.pythonhosted.org/packages/92/75/ce35194d8e3022203cca0d2f896dbb88689f9b3fce8e9f9cff942913519d/nltk-3.5.zip
Summary  : Natural Language Toolkit
Group    : Development/Tools
License  : Apache-2.0
Requires: nltk-bin = %{version}-%{release}
Requires: nltk-license = %{version}-%{release}
Requires: nltk-python = %{version}-%{release}
Requires: nltk-python3 = %{version}-%{release}
Requires: click
Requires: gensim
Requires: joblib
Requires: matplotlib
Requires: numpy
Requires: pyparsing
Requires: python-crfsuite
Requires: regex
Requires: requests
Requires: scikit-learn
Requires: scipy
Requires: tqdm
BuildRequires : buildreq-distutils3
BuildRequires : click
BuildRequires : gensim
BuildRequires : joblib
BuildRequires : matplotlib
BuildRequires : numpy
BuildRequires : pyparsing
BuildRequires : python-crfsuite
BuildRequires : regex
BuildRequires : requests
BuildRequires : scikit-learn
BuildRequires : scipy
BuildRequires : tqdm

%description
natural language processing.  NLTK requires Python 3.5, 3.6, 3.7, or 3.8.

%package bin
Summary: bin components for the nltk package.
Group: Binaries
Requires: nltk-license = %{version}-%{release}

%description bin
bin components for the nltk package.


%package license
Summary: license components for the nltk package.
Group: Default

%description license
license components for the nltk package.


%package python
Summary: python components for the nltk package.
Group: Default
Requires: nltk-python3 = %{version}-%{release}

%description python
python components for the nltk package.


%package python3
Summary: python3 components for the nltk package.
Group: Default
Requires: python3-core
Provides: pypi(nltk)
Requires: pypi(click)
Requires: pypi(joblib)
Requires: pypi(regex)
Requires: pypi(tqdm)

%description python3
python3 components for the nltk package.


%prep
%setup -q -n nltk-3.5
cd %{_builddir}/nltk-3.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1595895790
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/nltk
cp %{_builddir}/nltk-3.5/LICENSE.txt %{buildroot}/usr/share/package-licenses/nltk/811adb87e78ecb654eef43925884733aedc0af4d
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/nltk

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/nltk/811adb87e78ecb654eef43925884733aedc0af4d

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
